name: helm install

on:
    push:
        branches:
            - main
            

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: helm deploy
        uses: netf/helm-eks-action@v1
        with:
          cluster-name: eks-spot-terra1
          command: helm install --generate-name ./host
